name: Build and Deploy Docs

on:
  push:
    branches: [master]

env:
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-docs:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # Need permissions to read actions and pull requests
    permissions:
      actions: read
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your desired Node version
