name: Build and Deploy to S3

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 23.9.0
  AWS_REGION: eu-central-1
  S3_BUCKET: ohif-viewer-obz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm 11.4.2
        run: npm install -g npm@11.4.2

      - name: Install dependencies
        # This will now succeed because the committed yarn.lock is correct.
        # --frozen-lockfile ensures the build is fast and reproducible.
        run: yarn install --frozen-lockfile --no-integrity-checks

      - name: Build application
        run: yarn run build:ci

      # --- The rest of your deployment steps remain the same ---
      - name: Configure AWS credentials via OIDC
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-OHIF-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          aws s3 sync platform/app/dist/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "*.html" \
            --exclude "*.json"
          
          aws s3 sync platform/app/dist/ s3://${{ env.S3_BUCKET }}/ \
            --exclude "*" \
            --include "*.html" \
            --include "*.json" \
            --cache-control "no-cache, no-store, must-revalidate"

      - name: Invalidate CloudFront (optional)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          if [ ! -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            aws cloudfront create-invalidation \
              --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
              --paths "/*"
          else
            echo "CloudFront distribution ID not configured, skipping invalidation"
          fi

      - name: Output deployment info
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          echo "🚀 Deployment complete!"
          echo "S3 Website URL: http://${{ env.S3_BUCKET }}.s3-website.${{ env.AWS_REGION }}.amazonaws.com"
          if [ ! -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            echo "CloudFront invalidation initiated for distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          fi